### ISSUE TITLE
Stuck on Thursday

### ISSUE THREAD

**Issue by martinbutcher51** [jamieaconn/isthedartrunning#28]
Looks like the code has frozen as the website has been stuck on the same day all week

**Comment by jamieaconn** [comment]
Thanks saw this earlier. Hope to fix tonight but think there’s some missing data so will be a few days until it’s back up and running properly

**Comment by martinbutcher51** [comment]
🙏👍

**Comment by jamieaconn** [comment]
This is fixed - although I am missing rain data for the last few days so the output will look a bit odd for the next day I expect

**Comment by martinbutcher51** [comment]
Thanks Jamie it is very appreciated.
I will give it a trial run this morning.
Martin
